WeddingPlanner\CoreBundle\Entity\Guest:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        category:
            type: smallint
        invitationStatus:
            type: smallint
        response:
            type: boolean
            nullable: true
        needTransport:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
